# -*- coding: utf-8 -*-
"""EXP_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tj-0mzI-CHs8EHYOBIoBCCa_8QfzIObZ
"""

# ============================================================
# EXPERIMENT 5
# Implement Resampling Techniques and Confidence Interval
# Estimation for Statistical Decision Making
# ============================================================

# -----------------------------
# IMPORT REQUIRED LIBRARIES
# -----------------------------

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns


# ============================================================
# 1. LOAD DATASET
# ============================================================

df = pd.read_csv("/content/sample_data/diabetes.csv")

print("First 5 Records:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)


# ============================================================
# 2. SELECT NUMERICAL VARIABLE
# ============================================================

# We select Glucose for bootstrap analysis

glucose = df["Glucose"].dropna()

print("\n==============================")
print("SELECTED VARIABLE: GLUCOSE")
print("==============================")

print("Number of observations:", len(glucose))
print("Original Sample Mean:", glucose.mean())
print("Original Sample Standard Deviation:", glucose.std())


# ============================================================
# 3. BOOTSTRAP RESAMPLING
# ============================================================

np.random.seed(42)

n_bootstrap = 10000

bootstrap_means = []

for i in range(n_bootstrap):

    # Create bootstrap sample with replacement
    sample = np.random.choice(
        glucose,
        size=len(glucose),
        replace=True
    )

    # Calculate mean of bootstrap sample
    bootstrap_mean = sample.mean()

    bootstrap_means.append(bootstrap_mean)

# Convert list to NumPy array
bootstrap_means = np.array(bootstrap_means)

print("\n==============================")
print("BOOTSTRAP RESAMPLING")
print("==============================")

print("Number of Bootstrap Samples:",
      n_bootstrap)

print("Original Sample Mean:",
      glucose.mean())

print("Mean of Bootstrap Distribution:",
      bootstrap_means.mean())


# ============================================================
# 4. BOOTSTRAP 95% CONFIDENCE INTERVAL
# ============================================================

lower = np.percentile(
    bootstrap_means,
    2.5
)

upper = np.percentile(
    bootstrap_means,
    97.5
)

print("\n==============================")
print("95% BOOTSTRAP CONFIDENCE INTERVAL")
print("==============================")

print("Lower Bound:", lower)
print("Upper Bound:", upper)

print(
    f"95% Bootstrap Confidence Interval: "
    f"({lower:.2f}, {upper:.2f})"
)


# ============================================================
# 5. BOOTSTRAP DISTRIBUTION VISUALIZATION
# ============================================================

plt.figure(figsize=(10, 6))

sns.histplot(
    bootstrap_means,
    bins=50,
    kde=True
)

plt.axvline(
    glucose.mean(),
    linestyle="--",
    linewidth=2,
    label="Original Mean"
)

plt.axvline(
    lower,
    linestyle="--",
    linewidth=2,
    label="2.5% CI"
)

plt.axvline(
    upper,
    linestyle="--",
    linewidth=2,
    label="97.5% CI"
)

plt.title(
    "Bootstrap Distribution of Mean Glucose"
)

plt.xlabel("Bootstrap Mean Glucose")
plt.ylabel("Frequency")

plt.legend()

plt.show()


# ============================================================
# 6. DIVIDE DATA INTO TWO GROUPS
# ============================================================

# Outcome:
# 0 = Non-Diabetic
# 1 = Diabetic

diabetic = df[
    df["Outcome"] == 1
]["Glucose"].dropna()

non_diabetic = df[
    df["Outcome"] == 0
]["Glucose"].dropna()

print("\n==============================")
print("GROUP INFORMATION")
print("==============================")

print(
    "Number of Diabetic Patients:",
    len(diabetic)
)

print(
    "Number of Non-Diabetic Patients:",
    len(non_diabetic)
)

print(
    "\nMean Glucose - Diabetic:",
    diabetic.mean()
)

print(
    "Mean Glucose - Non-Diabetic:",
    non_diabetic.mean()
)


# ============================================================
# 7. CALCULATE OBSERVED DIFFERENCE
# ============================================================

observed_difference = (
    diabetic.mean()
    - non_diabetic.mean()
)

print("\n==============================")
print("OBSERVED DIFFERENCE")
print("==============================")

print(
    "Observed Difference in Mean Glucose:",
    observed_difference
)


# ============================================================
# 8. PERMUTATION TEST
# ============================================================

np.random.seed(42)

n_permutations = 10000

# Combine both groups
combined = np.concatenate(
    [
        diabetic.values,
        non_diabetic.values
    ]
)

# Number of observations in diabetic group
n_diabetic = len(diabetic)

permutation_differences = []

for i in range(n_permutations):

    # Randomly shuffle the combined data
    shuffled = np.random.permutation(
        combined
    )

    # Divide shuffled data into two groups
    shuffled_diabetic = shuffled[
        :n_diabetic
    ]

    shuffled_non_diabetic = shuffled[
        n_diabetic:
    ]

    # Calculate difference in means
    difference = (
        shuffled_diabetic.mean()
        - shuffled_non_diabetic.mean()
    )

    permutation_differences.append(
        difference
    )

# Convert to NumPy array
permutation_differences = np.array(
    permutation_differences
)

print("\n==============================")
print("PERMUTATION TEST")
print("==============================")

print(
    "Number of Permutations:",
    n_permutations
)

print("Permutation Test Completed.")


# ============================================================
# 9. CALCULATE PERMUTATION P-VALUE
# ============================================================

p_value = np.mean(
    np.abs(permutation_differences)
    >= abs(observed_difference)
)

alpha = 0.05

print("\n==============================")
print("PERMUTATION TEST RESULTS")
print("==============================")

print(
    "Observed Difference:",
    observed_difference
)

print(
    "P-value:",
    p_value
)

print(
    "Significance Level (alpha):",
    alpha
)


# ============================================================
# 10. HYPOTHESIS DECISION
# ============================================================

print("\n==============================")
print("HYPOTHESIS TEST DECISION")
print("==============================")

print(
    "H0: There is no significant difference "
    "in mean glucose between diabetic and "
    "non-diabetic groups."
)

print(
    "H1: There is a significant difference "
    "in mean glucose between diabetic and "
    "non-diabetic groups."
)

if p_value < alpha:

    print("\nDecision: Reject H0")

    print(
        "Conclusion: There is sufficient "
        "statistical evidence that the mean "
        "glucose levels differ between "
        "diabetic and non-diabetic groups."
    )

else:

    print("\nDecision: Fail to Reject H0")

    print(
        "Conclusion: There is insufficient "
        "statistical evidence to conclude "
        "that the mean glucose levels differ "
        "between the two groups."
    )


# ============================================================
# 11. PERMUTATION DISTRIBUTION VISUALIZATION
# ============================================================

plt.figure(figsize=(10, 6))

sns.histplot(
    permutation_differences,
    bins=50,
    kde=True
)

plt.axvline(
    observed_difference,
    linestyle="--",
    linewidth=2,
    label="Observed Difference"
)

plt.axvline(
    -observed_difference,
    linestyle="--",
    linewidth=2
)

plt.title(
    "Permutation Distribution of Mean Glucose Difference"
)

plt.xlabel(
    "Difference in Mean Glucose"
)

plt.ylabel("Frequency")

plt.legend()

plt.show()


# ============================================================
# 12. FINAL SUMMARY
# ============================================================

print("\n")
print("====================================================")
print("             EXPERIMENT 5 - FINAL RESULTS")
print("====================================================")

print("\nBOOTSTRAP RESULTS")
print("--------------------------------------------")

print(
    f"Original Mean Glucose: "
    f"{glucose.mean():.2f}"
)

print(
    f"Bootstrap Mean: "
    f"{bootstrap_means.mean():.2f}"
)

print(
    f"95% Bootstrap Confidence Interval: "
    f"({lower:.2f}, {upper:.2f})"
)

print("\nPERMUTATION TEST RESULTS")
print("--------------------------------------------")

print(
    f"Mean Glucose - Diabetic: "
    f"{diabetic.mean():.2f}"
)

print(
    f"Mean Glucose - Non-Diabetic: "
    f"{non_diabetic.mean():.2f}"
)

print(
    f"Observed Difference: "
    f"{observed_difference:.2f}"
)

print(
    f"Permutation P-value: "
    f"{p_value:.6f}"
)

print(
    f"Significance Level: "
    f"{alpha}"
)

if p_value < alpha:
    print("Final Decision: Reject H0")
else:
    print("Final Decision: Fail to Reject H0")

print("====================================================")
print("                 EXPERIMENT COMPLETED")
print("====================================================")